version: '3'
services:
  mysql:
    image: mysql:8
    container_name: re-logging-mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
